// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class COVIDataTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void COVIData() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 985));
    driver.findElement(By.linkText("COVID Data by Country")).click();
    driver.findElement(By.id("select2-country-container")).click();
    driver.findElement(By.id("submit")).click();

    assertThat(driver.findElement(By.id("country_text")).getText(), is("SOUTH AFRICA"));
    assertThat(driver.findElement(By.cssSelector(".mt-2")).getText(), is("ANALYSE SOME DATA CONCERNING THE COUNTRY'S COVID DATA"));
    assertThat(driver.findElement(By.cssSelector(".mt-md-0 b")).getText(), is("TOTAL CASES"));
    assertThat(driver.findElement(By.cssSelector(".col-lb-4:nth-child(3) b")).getText(), is("NEW CASES"));
    assertThat(driver.findElement(By.cssSelector(".col-lb-4:nth-child(4) b")).getText(), is("TOTAL DEATHS"));
    assertThat(driver.findElement(By.cssSelector(".col-lb-4:nth-child(7) b")).getText(), is("NEW DEATHS"));
    assertThat(driver.findElement(By.cssSelector(".col-lb-4:nth-child(6) b")).getText(), is("TOTAL TESTS"));
    assertThat(driver.findElement(By.cssSelector(".col-lb-4:nth-child(5) b")).getText(), is("NEW TESTS"));
  }
}
